export const goalieStats = {
  8475883: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [],
      },
    ],
  },
  8476316: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 29,
              powerPlaySaves: 0,
              shortHandedSaves: 0,
              evenSaves: 29,
              shortHandedShots: 0,
              evenShots: 30,
              powerPlayShots: 0,
              decision: 'W',
              savePercentage: 0.966667,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 30,
              goalsAgainst: 1,
              evenStrengthSavePercentage: 96.66666666666667,
            },
            team: {
              id: 54,
              name: 'Vegas Golden Knights',
              link: '/api/v1/teams/54',
            },
            opponent: {
              id: 52,
              name: 'Winnipeg Jets',
              link: '/api/v1/teams/52',
            },
            date: '2023-04-27',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030175,
              link: '/api/v1/game/2022030175/feed/live',
              content: {
                link: '/api/v1/game/2022030175/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 24,
              powerPlaySaves: 2,
              shortHandedSaves: 0,
              evenSaves: 22,
              shortHandedShots: 0,
              evenShots: 22,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.923077,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 26,
              goalsAgainst: 2,
              powerPlaySavePercentage: 50,
              evenStrengthSavePercentage: 100,
            },
            team: {
              id: 54,
              name: 'Vegas Golden Knights',
              link: '/api/v1/teams/54',
            },
            opponent: {
              id: 52,
              name: 'Winnipeg Jets',
              link: '/api/v1/teams/52',
            },
            date: '2023-04-24',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030174,
              link: '/api/v1/game/2022030174/feed/live',
              content: {
                link: '/api/v1/game/2022030174/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '83:14',
              ot: 0,
              shutouts: 0,
              saves: 30,
              powerPlaySaves: 8,
              shortHandedSaves: 0,
              evenSaves: 22,
              shortHandedShots: 0,
              evenShots: 25,
              powerPlayShots: 9,
              decision: 'W',
              savePercentage: 0.882353,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 34,
              goalsAgainst: 4,
              powerPlaySavePercentage: 88.88888888888889,
              evenStrengthSavePercentage: 88,
            },
            team: {
              id: 54,
              name: 'Vegas Golden Knights',
              link: '/api/v1/teams/54',
            },
            opponent: {
              id: 52,
              name: 'Winnipeg Jets',
              link: '/api/v1/teams/52',
            },
            date: '2023-04-22',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030173,
              link: '/api/v1/game/2022030173/feed/live',
              content: {
                link: '/api/v1/game/2022030173/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:50',
              ot: 0,
              shutouts: 0,
              saves: 31,
              powerPlaySaves: 3,
              shortHandedSaves: 1,
              evenSaves: 27,
              shortHandedShots: 1,
              evenShots: 28,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.939394,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 33,
              goalsAgainst: 2,
              powerPlaySavePercentage: 75,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 96.42857142857143,
            },
            team: {
              id: 54,
              name: 'Vegas Golden Knights',
              link: '/api/v1/teams/54',
            },
            opponent: {
              id: 52,
              name: 'Winnipeg Jets',
              link: '/api/v1/teams/52',
            },
            date: '2023-04-20',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030172,
              link: '/api/v1/game/2022030172/feed/live',
              content: {
                link: '/api/v1/game/2022030172/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '58:47',
              ot: 0,
              shutouts: 0,
              saves: 26,
              powerPlaySaves: 4,
              shortHandedSaves: 1,
              evenSaves: 21,
              shortHandedShots: 1,
              evenShots: 24,
              powerPlayShots: 5,
              decision: 'L',
              savePercentage: 0.866667,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 30,
              goalsAgainst: 4,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 87.5,
            },
            team: {
              id: 54,
              name: 'Vegas Golden Knights',
              link: '/api/v1/teams/54',
            },
            opponent: {
              id: 52,
              name: 'Winnipeg Jets',
              link: '/api/v1/teams/52',
            },
            date: '2023-04-18',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030171,
              link: '/api/v1/game/2022030171/feed/live',
              content: {
                link: '/api/v1/game/2022030171/content',
              },
            },
          },
        ],
      },
    ],
  },
  8476883: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 28,
              powerPlaySaves: 5,
              shortHandedSaves: 0,
              evenSaves: 23,
              shortHandedShots: 0,
              evenShots: 25,
              powerPlayShots: 5,
              decision: 'W',
              savePercentage: 0.933333,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 30,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 92,
            },
            team: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            opponent: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            date: '2023-04-27',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030125,
              link: '/api/v1/game/2022030125/feed/live',
              content: {
                link: '/api/v1/game/2022030125/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '64:14',
              ot: 0,
              shutouts: 0,
              saves: 32,
              powerPlaySaves: 5,
              shortHandedSaves: 2,
              evenSaves: 25,
              shortHandedShots: 2,
              evenShots: 28,
              powerPlayShots: 7,
              decision: 'L',
              savePercentage: 0.864865,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 37,
              goalsAgainst: 5,
              powerPlaySavePercentage: 71.42857142857143,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 89.28571428571429,
            },
            team: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            opponent: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            date: '2023-04-24',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030124,
              link: '/api/v1/game/2022030124/feed/live',
              content: {
                link: '/api/v1/game/2022030124/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '78:59',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 3,
              shortHandedSaves: 0,
              evenSaves: 20,
              shortHandedShots: 0,
              evenShots: 24,
              powerPlayShots: 3,
              decision: 'L',
              savePercentage: 0.851852,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 27,
              goalsAgainst: 4,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 83.33333333333334,
            },
            team: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            opponent: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            date: '2023-04-22',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030123,
              link: '/api/v1/game/2022030123/feed/live',
              content: {
                link: '/api/v1/game/2022030123/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 30,
              powerPlaySaves: 5,
              shortHandedSaves: 0,
              evenSaves: 25,
              shortHandedShots: 0,
              evenShots: 30,
              powerPlayShots: 7,
              decision: 'L',
              savePercentage: 0.810811,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 37,
              goalsAgainst: 7,
              powerPlaySavePercentage: 71.42857142857143,
              evenStrengthSavePercentage: 83.33333333333334,
            },
            team: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            opponent: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            date: '2023-04-20',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030122,
              link: '/api/v1/game/2022030122/feed/live',
              content: {
                link: '/api/v1/game/2022030122/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 28,
              powerPlaySaves: 5,
              shortHandedSaves: 1,
              evenSaves: 22,
              shortHandedShots: 1,
              evenShots: 23,
              powerPlayShots: 7,
              decision: 'W',
              savePercentage: 0.903226,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 31,
              goalsAgainst: 3,
              powerPlaySavePercentage: 71.42857142857143,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 95.65217391304348,
            },
            team: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            opponent: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            date: '2023-04-18',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030121,
              link: '/api/v1/game/2022030121/feed/live',
              content: {
                link: '/api/v1/game/2022030121/content',
              },
            },
          },
        ],
      },
    ],
  },
  8476999: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '65:50',
              ot: 0,
              shutouts: 0,
              saves: 21,
              powerPlaySaves: 1,
              shortHandedSaves: 0,
              evenSaves: 20,
              shortHandedShots: 0,
              evenShots: 23,
              powerPlayShots: 2,
              decision: 'L',
              savePercentage: 0.84,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 25,
              goalsAgainst: 4,
              powerPlaySavePercentage: 50,
              evenStrengthSavePercentage: 86.95652173913044,
            },
            team: {
              id: 6,
              name: 'Boston Bruins',
              link: '/api/v1/teams/6',
            },
            opponent: {
              id: 13,
              name: 'Florida Panthers',
              link: '/api/v1/teams/13',
            },
            date: '2023-04-26',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030115,
              link: '/api/v1/game/2022030115/feed/live',
              content: {
                link: '/api/v1/game/2022030115/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '56:49',
              ot: 0,
              shutouts: 0,
              saves: 41,
              powerPlaySaves: 10,
              shortHandedSaves: 0,
              evenSaves: 31,
              shortHandedShots: 0,
              evenShots: 32,
              powerPlayShots: 11,
              decision: 'W',
              savePercentage: 0.953488,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 43,
              goalsAgainst: 2,
              powerPlaySavePercentage: 90.9090909090909,
              evenStrengthSavePercentage: 96.875,
            },
            team: {
              id: 6,
              name: 'Boston Bruins',
              link: '/api/v1/teams/6',
            },
            opponent: {
              id: 13,
              name: 'Florida Panthers',
              link: '/api/v1/teams/13',
            },
            date: '2023-04-23',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030114,
              link: '/api/v1/game/2022030114/feed/live',
              content: {
                link: '/api/v1/game/2022030114/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 29,
              powerPlaySaves: 4,
              shortHandedSaves: 3,
              evenSaves: 22,
              shortHandedShots: 4,
              evenShots: 23,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.935484,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 31,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 75,
              evenStrengthSavePercentage: 95.65217391304348,
            },
            team: {
              id: 6,
              name: 'Boston Bruins',
              link: '/api/v1/teams/6',
            },
            opponent: {
              id: 13,
              name: 'Florida Panthers',
              link: '/api/v1/teams/13',
            },
            date: '2023-04-21',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030113,
              link: '/api/v1/game/2022030113/feed/live',
              content: {
                link: '/api/v1/game/2022030113/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '58:34',
              ot: 0,
              shutouts: 0,
              saves: 24,
              powerPlaySaves: 4,
              shortHandedSaves: 2,
              evenSaves: 18,
              shortHandedShots: 2,
              evenShots: 23,
              powerPlayShots: 4,
              decision: 'L',
              savePercentage: 0.827586,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 5,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 78.26086956521739,
            },
            team: {
              id: 6,
              name: 'Boston Bruins',
              link: '/api/v1/teams/6',
            },
            opponent: {
              id: 13,
              name: 'Florida Panthers',
              link: '/api/v1/teams/13',
            },
            date: '2023-04-19',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030112,
              link: '/api/v1/game/2022030112/feed/live',
              content: {
                link: '/api/v1/game/2022030112/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 31,
              powerPlaySaves: 0,
              shortHandedSaves: 2,
              evenSaves: 29,
              shortHandedShots: 2,
              evenShots: 30,
              powerPlayShots: 0,
              decision: 'W',
              savePercentage: 0.96875,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 32,
              goalsAgainst: 1,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 96.66666666666667,
            },
            team: {
              id: 6,
              name: 'Boston Bruins',
              link: '/api/v1/teams/6',
            },
            opponent: {
              id: 13,
              name: 'Florida Panthers',
              link: '/api/v1/teams/13',
            },
            date: '2023-04-17',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030111,
              link: '/api/v1/game/2022030111/feed/live',
              content: {
                link: '/api/v1/game/2022030111/content',
              },
            },
          },
        ],
      },
    ],
  },
  8477293: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '56:59',
              ot: 0,
              shutouts: 0,
              saves: 19,
              powerPlaySaves: 0,
              shortHandedSaves: 2,
              evenSaves: 17,
              shortHandedShots: 2,
              evenShots: 20,
              powerPlayShots: 0,
              decision: 'L',
              savePercentage: 0.863636,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 22,
              goalsAgainst: 3,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 85,
            },
            team: {
              id: 12,
              name: 'Carolina Hurricanes',
              link: '/api/v1/teams/12',
            },
            opponent: {
              id: 2,
              name: 'New York Islanders',
              link: '/api/v1/teams/2',
            },
            date: '2023-04-25',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030135,
              link: '/api/v1/game/2022030135/feed/live',
              content: {
                link: '/api/v1/game/2022030135/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 27,
              powerPlaySaves: 2,
              shortHandedSaves: 1,
              evenSaves: 24,
              shortHandedShots: 2,
              evenShots: 25,
              powerPlayShots: 2,
              decision: 'W',
              savePercentage: 0.931034,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 50,
              evenStrengthSavePercentage: 96,
            },
            team: {
              id: 12,
              name: 'Carolina Hurricanes',
              link: '/api/v1/teams/12',
            },
            opponent: {
              id: 2,
              name: 'New York Islanders',
              link: '/api/v1/teams/2',
            },
            date: '2023-04-23',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030134,
              link: '/api/v1/game/2022030134/feed/live',
              content: {
                link: '/api/v1/game/2022030134/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:18',
              ot: 0,
              shutouts: 0,
              saves: 32,
              powerPlaySaves: 9,
              shortHandedSaves: 0,
              evenSaves: 23,
              shortHandedShots: 0,
              evenShots: 26,
              powerPlayShots: 10,
              decision: 'L',
              savePercentage: 0.888889,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 36,
              goalsAgainst: 4,
              powerPlaySavePercentage: 90,
              evenStrengthSavePercentage: 88.46153846153845,
            },
            team: {
              id: 12,
              name: 'Carolina Hurricanes',
              link: '/api/v1/teams/12',
            },
            opponent: {
              id: 2,
              name: 'New York Islanders',
              link: '/api/v1/teams/2',
            },
            date: '2023-04-21',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030133,
              link: '/api/v1/game/2022030133/feed/live',
              content: {
                link: '/api/v1/game/2022030133/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '65:03',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 0,
              shortHandedSaves: 1,
              evenSaves: 22,
              shortHandedShots: 1,
              evenShots: 25,
              powerPlayShots: 0,
              decision: 'W',
              savePercentage: 0.884615,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 26,
              goalsAgainst: 3,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 88,
            },
            team: {
              id: 12,
              name: 'Carolina Hurricanes',
              link: '/api/v1/teams/12',
            },
            opponent: {
              id: 2,
              name: 'New York Islanders',
              link: '/api/v1/teams/2',
            },
            date: '2023-04-19',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030132,
              link: '/api/v1/game/2022030132/feed/live',
              content: {
                link: '/api/v1/game/2022030132/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 25,
              powerPlaySaves: 4,
              shortHandedSaves: 1,
              evenSaves: 20,
              shortHandedShots: 1,
              evenShots: 21,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.961538,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 26,
              goalsAgainst: 1,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 95.23809523809523,
            },
            team: {
              id: 12,
              name: 'Carolina Hurricanes',
              link: '/api/v1/teams/12',
            },
            opponent: {
              id: 2,
              name: 'New York Islanders',
              link: '/api/v1/teams/2',
            },
            date: '2023-04-17',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030131,
              link: '/api/v1/game/2022030131/feed/live',
              content: {
                link: '/api/v1/game/2022030131/content',
              },
            },
          },
        ],
      },
    ],
  },
  8477970: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 25,
              powerPlaySaves: 8,
              shortHandedSaves: 1,
              evenSaves: 16,
              shortHandedShots: 1,
              evenShots: 19,
              powerPlayShots: 10,
              decision: 'L',
              savePercentage: 0.833333,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 30,
              goalsAgainst: 5,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 84.21052631578947,
            },
            team: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            opponent: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            date: '2023-04-20',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030142,
              link: '/api/v1/game/2022030142/feed/live',
              content: {
                link: '/api/v1/game/2022030142/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:31',
              ot: 0,
              shutouts: 0,
              saves: 18,
              powerPlaySaves: 2,
              shortHandedSaves: 3,
              evenSaves: 13,
              shortHandedShots: 3,
              evenShots: 15,
              powerPlayShots: 4,
              decision: 'L',
              savePercentage: 0.818182,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 22,
              goalsAgainst: 4,
              powerPlaySavePercentage: 50,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 86.66666666666667,
            },
            team: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            opponent: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            date: '2023-04-18',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030141,
              link: '/api/v1/game/2022030141/feed/live',
              content: {
                link: '/api/v1/game/2022030141/content',
              },
            },
          },
        ],
      },
    ],
  },
  8478048: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:14',
              ot: 0,
              shutouts: 0,
              saves: 39,
              powerPlaySaves: 11,
              shortHandedSaves: 0,
              evenSaves: 28,
              shortHandedShots: 1,
              evenShots: 29,
              powerPlayShots: 12,
              decision: 'L',
              savePercentage: 0.928571,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 42,
              goalsAgainst: 3,
              powerPlaySavePercentage: 91.66666666666666,
              shortHandedSavePercentage: 0,
              evenStrengthSavePercentage: 96.55172413793103,
            },
            team: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            opponent: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            date: '2023-04-27',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030145,
              link: '/api/v1/game/2022030145/feed/live',
              content: {
                link: '/api/v1/game/2022030145/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '58:32',
              ot: 0,
              shutouts: 0,
              saves: 20,
              powerPlaySaves: 2,
              shortHandedSaves: 0,
              evenSaves: 18,
              shortHandedShots: 0,
              evenShots: 20,
              powerPlayShots: 2,
              decision: 'L',
              savePercentage: 0.909091,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 22,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 90,
            },
            team: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            opponent: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            date: '2023-04-24',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030144,
              link: '/api/v1/game/2022030144/feed/live',
              content: {
                link: '/api/v1/game/2022030144/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '71:06',
              ot: 0,
              shutouts: 0,
              saves: 26,
              powerPlaySaves: 1,
              shortHandedSaves: 2,
              evenSaves: 23,
              shortHandedShots: 2,
              evenShots: 24,
              powerPlayShots: 2,
              decision: 'L',
              savePercentage: 0.928571,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 28,
              goalsAgainst: 2,
              powerPlaySavePercentage: 50,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 95.83333333333334,
            },
            team: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            opponent: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            date: '2023-04-22',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030143,
              link: '/api/v1/game/2022030143/feed/live',
              content: {
                link: '/api/v1/game/2022030143/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 3,
              shortHandedSaves: 0,
              evenSaves: 20,
              shortHandedShots: 0,
              evenShots: 20,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.958333,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 1,
              powerPlaySavePercentage: 75,
              evenStrengthSavePercentage: 100,
            },
            team: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            opponent: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            date: '2023-04-20',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030142,
              link: '/api/v1/game/2022030142/feed/live',
              content: {
                link: '/api/v1/game/2022030142/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:49',
              ot: 0,
              shutouts: 0,
              saves: 27,
              powerPlaySaves: 0,
              shortHandedSaves: 0,
              evenSaves: 27,
              shortHandedShots: 0,
              evenShots: 28,
              powerPlayShots: 0,
              decision: 'W',
              savePercentage: 0.964286,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 28,
              goalsAgainst: 1,
              evenStrengthSavePercentage: 96.42857142857143,
            },
            team: {
              id: 3,
              name: 'New York Rangers',
              link: '/api/v1/teams/3',
            },
            opponent: {
              id: 1,
              name: 'New Jersey Devils',
              link: '/api/v1/teams/1',
            },
            date: '2023-04-18',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030141,
              link: '/api/v1/game/2022030141/feed/live',
              content: {
                link: '/api/v1/game/2022030141/content',
              },
            },
          },
        ],
      },
    ],
  },
  8478492: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '56:20',
              ot: 0,
              shutouts: 0,
              saves: 34,
              powerPlaySaves: 6,
              shortHandedSaves: 4,
              evenSaves: 24,
              shortHandedShots: 4,
              evenShots: 27,
              powerPlayShots: 6,
              decision: 'L',
              savePercentage: 0.918919,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 37,
              goalsAgainst: 3,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 88.88888888888889,
            },
            team: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            opponent: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            date: '2023-04-27',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030125,
              link: '/api/v1/game/2022030125/feed/live',
              content: {
                link: '/api/v1/game/2022030125/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '63:55',
              ot: 0,
              shutouts: 0,
              saves: 27,
              powerPlaySaves: 3,
              shortHandedSaves: 2,
              evenSaves: 22,
              shortHandedShots: 2,
              evenShots: 25,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.870968,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 31,
              goalsAgainst: 4,
              powerPlaySavePercentage: 75,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 88,
            },
            team: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            opponent: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            date: '2023-04-24',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030124,
              link: '/api/v1/game/2022030124/feed/live',
              content: {
                link: '/api/v1/game/2022030124/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '78:43',
              ot: 0,
              shutouts: 0,
              saves: 36,
              powerPlaySaves: 4,
              shortHandedSaves: 1,
              evenSaves: 31,
              shortHandedShots: 1,
              evenShots: 34,
              powerPlayShots: 4,
              decision: 'W',
              savePercentage: 0.923077,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 39,
              goalsAgainst: 3,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 91.17647058823529,
            },
            team: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            opponent: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            date: '2023-04-22',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030123,
              link: '/api/v1/game/2022030123/feed/live',
              content: {
                link: '/api/v1/game/2022030123/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:33',
              ot: 0,
              shutouts: 0,
              saves: 20,
              powerPlaySaves: 2,
              shortHandedSaves: 0,
              evenSaves: 18,
              shortHandedShots: 0,
              evenShots: 20,
              powerPlayShots: 2,
              decision: 'W',
              savePercentage: 0.909091,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 22,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 90,
            },
            team: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            opponent: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            date: '2023-04-20',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030122,
              link: '/api/v1/game/2022030122/feed/live',
              content: {
                link: '/api/v1/game/2022030122/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '40:00',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 9,
              shortHandedSaves: 0,
              evenSaves: 14,
              shortHandedShots: 0,
              evenShots: 16,
              powerPlayShots: 13,
              decision: 'L',
              savePercentage: 0.793103,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 6,
              powerPlaySavePercentage: 69.23076923076923,
              evenStrengthSavePercentage: 87.5,
            },
            team: {
              id: 10,
              name: 'Toronto Maple Leafs',
              link: '/api/v1/teams/10',
            },
            opponent: {
              id: 14,
              name: 'Tampa Bay Lightning',
              link: '/api/v1/teams/14',
            },
            date: '2023-04-18',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030121,
              link: '/api/v1/game/2022030121/feed/live',
              content: {
                link: '/api/v1/game/2022030121/content',
              },
            },
          },
        ],
      },
    ],
  },
  8479406: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:14',
              ot: 0,
              shutouts: 0,
              saves: 21,
              powerPlaySaves: 8,
              shortHandedSaves: 1,
              evenSaves: 12,
              shortHandedShots: 1,
              evenShots: 13,
              powerPlayShots: 10,
              decision: 'L',
              savePercentage: 0.875,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 3,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 92.3076923076923,
            },
            team: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            opponent: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            date: '2023-04-25',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030165,
              link: '/api/v1/game/2022030165/feed/live',
              content: {
                link: '/api/v1/game/2022030165/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '56:58',
              ot: 0,
              shutouts: 0,
              saves: 21,
              powerPlaySaves: 4,
              shortHandedSaves: 1,
              evenSaves: 16,
              shortHandedShots: 1,
              evenShots: 17,
              powerPlayShots: 6,
              decision: 'L',
              savePercentage: 0.875,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 3,
              powerPlaySavePercentage: 66.66666666666666,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 94.11764705882352,
            },
            team: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            opponent: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            date: '2023-04-23',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030164,
              link: '/api/v1/game/2022030164/feed/live',
              content: {
                link: '/api/v1/game/2022030164/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 2,
              shortHandedSaves: 0,
              evenSaves: 21,
              shortHandedShots: 0,
              evenShots: 22,
              powerPlayShots: 2,
              decision: 'W',
              savePercentage: 0.958333,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 1,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 95.45454545454545,
            },
            team: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            opponent: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            date: '2023-04-21',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030163,
              link: '/api/v1/game/2022030163/feed/live',
              content: {
                link: '/api/v1/game/2022030163/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '92:20',
              ot: 0,
              shutouts: 0,
              saves: 51,
              powerPlaySaves: 6,
              shortHandedSaves: 3,
              evenSaves: 42,
              shortHandedShots: 3,
              evenShots: 42,
              powerPlayShots: 8,
              decision: 'W',
              savePercentage: 0.962264,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 53,
              goalsAgainst: 2,
              powerPlaySavePercentage: 75,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 100,
            },
            team: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            opponent: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            date: '2023-04-17',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030161,
              link: '/api/v1/game/2022030161/feed/live',
              content: {
                link: '/api/v1/game/2022030161/content',
              },
            },
          },
        ],
      },
    ],
  },
  8479973: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:21',
              ot: 0,
              shutouts: 0,
              saves: 25,
              powerPlaySaves: 0,
              shortHandedSaves: 2,
              evenSaves: 23,
              shortHandedShots: 2,
              evenShots: 26,
              powerPlayShots: 0,
              decision: 'W',
              savePercentage: 0.892857,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 28,
              goalsAgainst: 3,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 88.46153846153845,
            },
            team: {
              id: 22,
              name: 'Edmonton Oilers',
              link: '/api/v1/teams/22',
            },
            opponent: {
              id: 26,
              name: 'Los Angeles Kings',
              link: '/api/v1/teams/26',
            },
            date: '2023-04-25',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030185,
              link: '/api/v1/game/2022030185/feed/live',
              content: {
                link: '/api/v1/game/2022030185/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '20:00',
              ot: 0,
              shutouts: 0,
              saves: 8,
              powerPlaySaves: 0,
              shortHandedSaves: 0,
              evenSaves: 8,
              shortHandedShots: 0,
              evenShots: 10,
              powerPlayShots: 1,
              savePercentage: 0.727273,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 11,
              goalsAgainst: 3,
              powerPlaySavePercentage: 0,
              evenStrengthSavePercentage: 80,
            },
            team: {
              id: 22,
              name: 'Edmonton Oilers',
              link: '/api/v1/teams/22',
            },
            opponent: {
              id: 26,
              name: 'Los Angeles Kings',
              link: '/api/v1/teams/26',
            },
            date: '2023-04-23',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030184,
              link: '/api/v1/game/2022030184/feed/live',
              content: {
                link: '/api/v1/game/2022030184/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '63:24',
              ot: 0,
              shutouts: 0,
              saves: 28,
              powerPlaySaves: 4,
              shortHandedSaves: 0,
              evenSaves: 24,
              shortHandedShots: 0,
              evenShots: 25,
              powerPlayShots: 6,
              decision: 'L',
              savePercentage: 0.903226,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 31,
              goalsAgainst: 3,
              powerPlaySavePercentage: 66.66666666666666,
              evenStrengthSavePercentage: 96,
            },
            team: {
              id: 22,
              name: 'Edmonton Oilers',
              link: '/api/v1/teams/22',
            },
            opponent: {
              id: 26,
              name: 'Los Angeles Kings',
              link: '/api/v1/teams/26',
            },
            date: '2023-04-21',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030183,
              link: '/api/v1/game/2022030183/feed/live',
              content: {
                link: '/api/v1/game/2022030183/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 22,
              powerPlaySaves: 3,
              shortHandedSaves: 0,
              evenSaves: 19,
              shortHandedShots: 0,
              evenShots: 21,
              powerPlayShots: 3,
              decision: 'W',
              savePercentage: 0.916667,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 90.47619047619048,
            },
            team: {
              id: 22,
              name: 'Edmonton Oilers',
              link: '/api/v1/teams/22',
            },
            opponent: {
              id: 26,
              name: 'Los Angeles Kings',
              link: '/api/v1/teams/26',
            },
            date: '2023-04-19',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030182,
              link: '/api/v1/game/2022030182/feed/live',
              content: {
                link: '/api/v1/game/2022030182/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '69:19',
              ot: 0,
              shutouts: 0,
              saves: 31,
              powerPlaySaves: 8,
              shortHandedSaves: 1,
              evenSaves: 22,
              shortHandedShots: 1,
              evenShots: 24,
              powerPlayShots: 10,
              decision: 'L',
              savePercentage: 0.885714,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 35,
              goalsAgainst: 4,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 91.66666666666666,
            },
            team: {
              id: 22,
              name: 'Edmonton Oilers',
              link: '/api/v1/teams/22',
            },
            opponent: {
              id: 26,
              name: 'Los Angeles Kings',
              link: '/api/v1/teams/26',
            },
            date: '2023-04-17',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030181,
              link: '/api/v1/game/2022030181/feed/live',
              content: {
                link: '/api/v1/game/2022030181/content',
              },
            },
          },
        ],
      },
    ],
  },
  8479979: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:53',
              ot: 0,
              shutouts: 1,
              saves: 27,
              powerPlaySaves: 6,
              shortHandedSaves: 1,
              evenSaves: 20,
              shortHandedShots: 1,
              evenShots: 20,
              powerPlayShots: 6,
              decision: 'W',
              savePercentage: 1,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 27,
              goalsAgainst: 0,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 100,
            },
            team: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            opponent: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            date: '2023-04-25',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030165,
              link: '/api/v1/game/2022030165/feed/live',
              content: {
                link: '/api/v1/game/2022030165/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:26',
              ot: 0,
              shutouts: 0,
              saves: 32,
              powerPlaySaves: 2,
              shortHandedSaves: 1,
              evenSaves: 29,
              shortHandedShots: 1,
              evenShots: 30,
              powerPlayShots: 3,
              decision: 'W',
              savePercentage: 0.941176,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 34,
              goalsAgainst: 2,
              powerPlaySavePercentage: 66.66666666666666,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 96.66666666666667,
            },
            team: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            opponent: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            date: '2023-04-23',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030164,
              link: '/api/v1/game/2022030164/feed/live',
              content: {
                link: '/api/v1/game/2022030164/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '57:07',
              ot: 0,
              shutouts: 0,
              saves: 20,
              powerPlaySaves: 4,
              shortHandedSaves: 1,
              evenSaves: 15,
              shortHandedShots: 1,
              evenShots: 18,
              powerPlayShots: 5,
              decision: 'L',
              savePercentage: 0.833333,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 24,
              goalsAgainst: 4,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 83.33333333333334,
            },
            team: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            opponent: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            date: '2023-04-21',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030163,
              link: '/api/v1/game/2022030163/feed/live',
              content: {
                link: '/api/v1/game/2022030163/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '59:42',
              ot: 0,
              shutouts: 0,
              saves: 23,
              powerPlaySaves: 8,
              shortHandedSaves: 2,
              evenSaves: 13,
              shortHandedShots: 2,
              evenShots: 15,
              powerPlayShots: 9,
              decision: 'W',
              savePercentage: 0.884615,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 26,
              goalsAgainst: 3,
              powerPlaySavePercentage: 88.88888888888889,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 86.66666666666667,
            },
            team: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            opponent: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            date: '2023-04-19',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030162,
              link: '/api/v1/game/2022030162/feed/live',
              content: {
                link: '/api/v1/game/2022030162/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '92:05',
              ot: 0,
              shutouts: 0,
              saves: 45,
              powerPlaySaves: 7,
              shortHandedSaves: 0,
              evenSaves: 38,
              shortHandedShots: 0,
              evenShots: 40,
              powerPlayShots: 8,
              decision: 'L',
              savePercentage: 0.9375,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 48,
              goalsAgainst: 3,
              powerPlaySavePercentage: 87.5,
              evenStrengthSavePercentage: 95,
            },
            team: {
              id: 25,
              name: 'Dallas Stars',
              link: '/api/v1/teams/25',
            },
            opponent: {
              id: 30,
              name: 'Minnesota Wild',
              link: '/api/v1/teams/30',
            },
            date: '2023-04-17',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030161,
              link: '/api/v1/game/2022030161/feed/live',
              content: {
                link: '/api/v1/game/2022030161/content',
              },
            },
          },
        ],
      },
    ],
  },
  8480382: {
    copyright: 'NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2023. All Rights Reserved.',
    stats: [
      {
        type: {
          displayName: 'playoffGameLog',
          gameType: null,
        },
        splits: [
          {
            season: '20222023',
            stat: {
              timeOnIce: '56:33',
              ot: 0,
              shutouts: 0,
              saves: 26,
              powerPlaySaves: 1,
              shortHandedSaves: 0,
              evenSaves: 25,
              shortHandedShots: 0,
              evenShots: 28,
              powerPlayShots: 1,
              decision: 'L',
              savePercentage: 0.896552,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 3,
              powerPlaySavePercentage: 100,
              evenStrengthSavePercentage: 89.28571428571429,
            },
            team: {
              id: 21,
              name: 'Colorado Avalanche',
              link: '/api/v1/teams/21',
            },
            opponent: {
              id: 55,
              name: 'Seattle Kraken',
              link: '/api/v1/teams/55',
            },
            date: '2023-04-26',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030155,
              link: '/api/v1/game/2022030155/feed/live',
              content: {
                link: '/api/v1/game/2022030155/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '63:00',
              ot: 0,
              shutouts: 0,
              saves: 40,
              powerPlaySaves: 8,
              shortHandedSaves: 1,
              evenSaves: 31,
              shortHandedShots: 1,
              evenShots: 32,
              powerPlayShots: 10,
              decision: 'L',
              savePercentage: 0.930233,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 43,
              goalsAgainst: 3,
              powerPlaySavePercentage: 80,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 96.875,
            },
            team: {
              id: 21,
              name: 'Colorado Avalanche',
              link: '/api/v1/teams/21',
            },
            opponent: {
              id: 55,
              name: 'Seattle Kraken',
              link: '/api/v1/teams/55',
            },
            date: '2023-04-24',
            isHome: false,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030154,
              link: '/api/v1/game/2022030154/feed/live',
              content: {
                link: '/api/v1/game/2022030154/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 25,
              powerPlaySaves: 2,
              shortHandedSaves: 0,
              evenSaves: 23,
              shortHandedShots: 0,
              evenShots: 26,
              powerPlayShots: 3,
              decision: 'W',
              savePercentage: 0.862069,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 4,
              powerPlaySavePercentage: 66.66666666666666,
              evenStrengthSavePercentage: 88.46153846153845,
            },
            team: {
              id: 21,
              name: 'Colorado Avalanche',
              link: '/api/v1/teams/21',
            },
            opponent: {
              id: 55,
              name: 'Seattle Kraken',
              link: '/api/v1/teams/55',
            },
            date: '2023-04-22',
            isHome: false,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030153,
              link: '/api/v1/game/2022030153/feed/live',
              content: {
                link: '/api/v1/game/2022030153/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '60:00',
              ot: 0,
              shutouts: 0,
              saves: 27,
              powerPlaySaves: 1,
              shortHandedSaves: 0,
              evenSaves: 26,
              shortHandedShots: 1,
              evenShots: 27,
              powerPlayShots: 1,
              decision: 'W',
              savePercentage: 0.931034,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 29,
              goalsAgainst: 2,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 0,
              evenStrengthSavePercentage: 96.29629629629629,
            },
            team: {
              id: 21,
              name: 'Colorado Avalanche',
              link: '/api/v1/teams/21',
            },
            opponent: {
              id: 55,
              name: 'Seattle Kraken',
              link: '/api/v1/teams/55',
            },
            date: '2023-04-20',
            isHome: true,
            isWin: true,
            isOT: false,
            game: {
              gamePk: 2022030152,
              link: '/api/v1/game/2022030152/feed/live',
              content: {
                link: '/api/v1/game/2022030152/content',
              },
            },
          },
          {
            season: '20222023',
            stat: {
              timeOnIce: '57:56',
              ot: 0,
              shutouts: 0,
              saves: 27,
              powerPlaySaves: 2,
              shortHandedSaves: 1,
              evenSaves: 24,
              shortHandedShots: 1,
              evenShots: 27,
              powerPlayShots: 2,
              decision: 'L',
              savePercentage: 0.9,
              games: 1,
              gamesStarted: 1,
              shotsAgainst: 30,
              goalsAgainst: 3,
              powerPlaySavePercentage: 100,
              shortHandedSavePercentage: 100,
              evenStrengthSavePercentage: 88.88888888888889,
            },
            team: {
              id: 21,
              name: 'Colorado Avalanche',
              link: '/api/v1/teams/21',
            },
            opponent: {
              id: 55,
              name: 'Seattle Kraken',
              link: '/api/v1/teams/55',
            },
            date: '2023-04-18',
            isHome: true,
            isWin: false,
            isOT: false,
            game: {
              gamePk: 2022030151,
              link: '/api/v1/game/2022030151/feed/live',
              content: {
                link: '/api/v1/game/2022030151/content',
              },
            },
          },
        ],
      },
    ],
  },
}
